name: Default Qt on ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/runner-images#available-images
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install qt5-default qtbase5-private-dev
    - name: build
      run: |
        mkdir build
        cd build
        qmake ../src
        make -j8